### ISSUE TITLE
Possible incompatibility with IDEA 14.1

### ISSUE THREAD

**Issue by denofevil** [CoreMedia/jangaroo-idea#1]
Hi,

I'm Dennis from WebStorm team. Our internal check indicated that your plugin v0.29 is using API that is not compatible with upcoming v14.1 EAP:

```
com.intellij.lang.javascript.psi.JSType com.intellij.lang.javascript.psi.resolve.JSResolveUtil#getTypeFromSetAccessor(com.intellij.lang.javascript.psi.JSNamedElement)
```

(in https://github.com/CoreMedia/jangaroo-idea/blob/a55ca59edb9780b5d82b9f9201d041775925b2cf/idea-plugin/src/main/java/net/jangaroo/ide/idea/exml/ExmlLanguageInjector.java)
Please contact me to receive nightly build and API migration advice if you want to adopt your plugin early.

**Comment by fwienber** [comment]
Thanks for the notification! We fixed that!
