### ISSUE TITLE
FileTemplate Issue in IDEA 14.1

### ISSUE THREAD

**Issue by jjordano** [CoreMedia/jangaroo-idea#2]
Hi,
   I'm using your plugin for coremedia studio development. Unfortunately there is a small issue. Your Plugin adds "File Templates" -> "ActionScript Class" and "ActionScript Interface" that already exists in IDEA. When I try to add some new Template (or change one) and try to apply changes ... an error in IDEA is shown (see attachment). 
![file-templates-duplicates](https://cloud.githubusercontent.com/assets/13675396/9108162/7fedca78-3c2c-11e5-9e05-abdf0e7a440d.png) 
Obviously I can't change the name of this template in IDEA so ... here I'm : 
Could you please change names of File-Templates in this Plugin:
jangaroo-idea/idea-plugin/src/main/java/fileTemplates/
"ActionScript Class" to ... whatever (e.g. "AS Class")
"ActionScript Interface" -> "AS Interface"  ? 
That would be great.

thanks
  JJ

**Comment by fwienber** [comment]
Continued in http://jangaroo.myjetbrains.com/youtrack/issue/IDEA-52
