### ISSUE TITLE
Possible error in intellij idea 2016.2

### ISSUE THREAD

**Issue by dbm0773** [CoreMedia/jangaroo-idea#8]
While trying to inject AS3 into <file>.exml.: com.intellij.lang.javascript.psi.JSParameterList.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;

**Comment by fwienber** [comment]
Thanks for reporting this. I have created an issue in the official Jangaroo bug tracker:
http://jangaroo.myjetbrains.com/youtrack/issue/IDEA-51
Let's continue analysing the problem there!
